CREATE TABLE IF NOT EXISTS `user_images` (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(150) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `data` LONGBLOB NOT NULL
  )